### ISSUE TITLE
Alben als Links

### ISSUE THREAD

**Issue by chris2345** [BerlinPix/filo#10]
Hallo,
ich habe eine Frage zu Ihrem Script „Filo Master“.
Wie bekomme ich es hin, dass auf der Startseite des Scripts keine Fotos angezeigt werden?
Es soll einfach eine Übersicht der Alben dargestellt werden bzw. Links zum Album:

- Profil Pictures
- Cover Photos
- Lost Places
- Traveling Thailand
- New Born

Erst bei Klick auf den Albumnamen sollen sich die darin befindlichen Fotos öffnen.
Über eine Antwort würde ich mich sehr freuen

Gruß
Chris

**Comment by erik-wendt** [comment]
Schau dir bitte dafür mal das [Beispiel 5](https://github.com/BerlinPix/filo/blob/master/examples/5-api-href-get.html) an. Hier wird der Benutzer von einer Übersichtsseite auf eine Album-Detailseite weitergeleitet. Wenn du nun möchtest dass am Anfang nur die Title der Alben zu sehen und verlinkt sind, musste du das noch ergänzen.

Dafür kannst du die Option "load" nutzen. Diese nimmt eine Funktion entgegen, welche ausgeführt wird nachdem alle Alben geladen wurden. Die Idee wäre also per CSS die Thumbnails auszublenden und per Click-Listener auf dem Title den Nutzer weiter zu leiten.

**Comment by chris2345** [comment]
Hallo Erik,

ich bin kann leider überhaupt kein Javascript. :-(
Damals auf Deiner alten Seite habe ich da was in den Komentaren gefunden, damit ging es. Das sah folgendermassen aus:

```
<script>
jQuery(function ($) {

	var options = {
		template: 1,
		href: 'album.php',
		excluded: ['profile pictures', 'cover photos', 'mobile uploads', 'timeline photos'],
        load: function () {
            $.each($('.filo .album'), function (index,value) {
                var h = $(value).attr('id');
                $(value).attr('id', unescape(encodeURIComponent(h)));
            });
        },
        container: '#photos'
	};
	$.filo('filojs', options);
});
</script>
```
```

<script>
jQuery(document).ready(function ($) {
	//get the url params
	var params = $.filo.getUrlParams();	
	//set up the options
	var options = {
		template: 1,
		albums: [params["album"]],
		maxCount: 'all',
		container: '#container'
	}	
	
	$.filo(params["profile"], options); //add to body
});
</script>
```

Könntest Du den Code evtl. anpassen?
Würde mich sehr freuen ...

Gruß
Chris

**Comment by erik-wendt** [comment]
OK verstehe. Ich habe das [Beispiel 5](https://github.com/BerlinPix/filo/blob/master/examples/5-api-href-get.html) dahingehend erweitert, dass eine Linkliste generiert wird. Die Lösung ist eher ein Hack aber funktioniert fürs Erste.

Hier wird allerdings für die Liste und das folgende Album die selbe Datei/Seite verwendet. Anbei noch mal die Datei als TXT.

```
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>API: albums - jQuery FILo</title>
<link rel="stylesheet" href="../build/filo_style.css" type="text/css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" language="javascript" type="text/javascript"></script>
<script src="../build/filo.js" type="text/javascript" language="javascript"></script>
<script>
$(function () {

	//get album name from url
	var album = $.filo.getUrlParameter('album')

	//set up the options
	var options = {
		facebookId: 'filojs',
		method: 'get'
	}	
    
    // generate link list out of album titles
    var generateLinkList = function () {
        $ul = $('<ul class="filo__link-list" />');
        $('.filo__album__title').each(function (index, title) {
            $ul.append('<li class="filo__link-item" ><a class="filo__link" href="?album=' + $(title).text() + '">' + $(title).text() + '</a></li>');    
        });  
        $('#js-filojs').after($ul).remove();
    };

	//if album name is set show only this one
	if (typeof album === 'string' && album.length > 0) {
		options.albums = [album];
	//else show link list
	} else {
        $('#js-filojs').hide();
		options.load = generateLinkList;
	}

	//start filo
	$('#js-filojs').filo(options);
});
</script>
<style>

    .filo__link-list {
        list-style: decimal;
    }
    
    .filo__link-item {
        margin-bottom: 10px;
    }
    
    .filo__link {
        color: tomato;
    }
    
</style>
</head>
<body>
	<!-- js example -->
	<div id="js-filojs"></div>
</body>
</html>
```


[generate-link-list.txt](https://github.com/BerlinPix/filo/files/464582/generate-link-list.txt)

**Comment by chris2345** [comment]
Hallo Erik,

vielen vielen Dank dafür. :+1: 

Gruß
Chris
