### ISSUE TITLE
[Q] I had a expired access token and changed usrp passw, now gives errors

### ISSUE THREAD

**Issue by schroef** [BerlinPix/filo#16]
I had to renew the access token and i also changed my user profile password. Now with a new access token i keep getting this error.

`"error": {
      "message": "Error validating access token: Session does not match current stored session. This may be because the user changed the password since the time the session was created or Facebook has changed the session for security reasons.",
      "type": "OAuthException",
      "code": 190,
      "error_subcode": 460,
      "fbtrace_id": "BQ8BDT7Y8r5"
   }
}`

What method/workflow most i do now?

**Comment by schroef** [comment]
Sorry i wasnt paying attention here. I had been editing the filo_min.js file and i loaded a old filo.js file. This one still had a old access token.

Sorry to bother you again

**Comment by erik-wendt** [comment]
Hey @schroef, 

no worries. just update to the new filo.js 2.1.2. Then you don't need an access token anymore.

**Comment by schroef** [comment]
okay, how is that possible then? I thought you needed such a token to get the access to the pictures. So know you can link them to any page actually without certain password or app?

**Comment by erik-wendt** [comment]
This is possible because of the proxy service as described here: https://github.com/BerlinPix/filo/#proxy-service

I don't have update log but I will think about that.

**Comment by erik-wendt** [comment]
I added a "[Updates](https://github.com/BerlinPix/filo#updates)" section in the readme
