### ISSUE TITLE
match problem

### ISSUE THREAD

**Issue by markus1971** [BerlinPix/filo#17]
it`s right?
if i have data-match="true" only the one album will shown?
have i change anything else?

in my case all albums with the word mintrop will shown.

`<div id="js-filojs"></div>
<div class="filo" data-facebook-id="mmHotels" data-max-count="100">
<div class="filo__album" data-album-name="Mintrops Stadt Hotel" data-match="true">
</div></div>`

**Comment by markus1971** [comment]
do you know this problem?

**Comment by erik-wendt** [comment]
If you're using **data-match="true"** then every album which contains the words "Mintrops Stadt Hotel" will be added. Without only the album with exact these word will be added.

See the [API Docs](https://github.com/BerlinPix/filo/#api) for that.

**Comment by markus1971** [comment]
done, with data-match="true" and without the result are the same.
[http://marvino.de/cgi-bin/baseportal.pl?htx=/aktionskalender/testkalender]

**Comment by erik-wendt** [comment]
OK - I think your'e using an older version of filo.js. The Option "matched" was added in the newest version 2.1.2. So please update and it should work as expected.

**Comment by markus1971** [comment]
done = works :-)
