### ISSUE TITLE
Error while loading, please check you Facebook-ID or write me

### ISSUE THREAD

**Issue by jeffjoe** [BerlinPix/filo#18]
Hello,
I used filo on my website, but now I got the following error message and no pic will show up
„Error while loading, please check you Facebook-ID or write me..." and "no profile is given, check the GET parameters"

Can you help me?
Thanks

**Comment by erik-wendt** [comment]
Which version are you using? The Version 1 is not working anymore because of a change in the Facebook Graph API. Please update to the newest version.

**Comment by jeffjoe** [comment]
Thanks for answering and giving the answer.
After an update, everything worked fine again.

sorry for answering so late...

**Comment by erik-wendt** [comment]
perfect!
