### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by markus1971** [BerlinPix/filo#22]
i use your script in this site.
path to the scripts are the same, only different fanpages and albums.
last week booth working?!?
markus

works
http://www.winterschlafkalender.de/tuerchen-05

works not
http://www.winterschlafkalender.de/tuerchen-20

**Comment by erik-wendt** [comment]
the second url "tuerchen-20" seems to use an invalid facebook ID "stephanshoehe". This facebook page doesn't exist.

https://www.facebook.com/stephanshoehe

**Comment by markus1971** [comment]
ok, they changed the name, but here is the same error:
http://www.musiklandschaftwestfalen.de/de-geschichte
fanpage and albums exists.

**Comment by erik-wendt** [comment]
does the problem still exists? it's looks like it's working now

**Comment by markus1971** [comment]
changed in a new fanpage, than works.
