### ISSUE TITLE
Load the " closed " albums instead of showing all the images on the page

### ISSUE THREAD

**Issue by PauloRobert** [BerlinPix/filo#3]
I have a website in bootstrap and want to get the albums within a div , but want only carry the covers of albums and photos to be arranged only if the user clicks on the album , thus avoiding polluting the page , how? Currently it carries all the photos already on the page .

**Comment by BerlinPix** [comment]
As I understand, you want have an album overview page like here: https://www.facebook.com/filojs/photos/?tab=albums

This you can create with the Options **maxCount** and **href**:

1. create the overview page with all the albums and show just few thumbnails (or just one) using **maxCount**
2. forward the user to new another page (could be the same) using **href** to define the URL. This will disable the "overlay on click" for this page
3. [OPTIONAL] set **method** to use **GET** or **POST** for the forwarding  

Take a look to the [href-get example](https://github.com/BerlinPix/filo/blob/master/examples/5-api-href-get.html) to get an idea of what i mean.

**Comment by schroef** [comment]
Can this also be done for keeping the gallery on the same page. Now when i use maxPreview, the hidden thumbs are clickable and also change the height of the div they are in.

http://amnesia.cw/index_2.html

**Comment by erik-wendt** [comment]
fixed by 3114929883ff260ecf0b982b31bd9a760751f6a2
